<?xml version="1.0" ?>
<robot name="fourWD_catbot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find catbot_description)/urdf/include/wheel.urdf.xacro" />
    <xacro:include filename="$(find catbot_description)/urdf/include/laser_scanner.urdf.xacro" />
    <xacro:include filename="$(find catbot_description)/urdf/include/camera.urdf.xacro" />
    <xacro:include filename="$(find catbot_description)/urdf/include/imu.urdf.xacro" />

    <property name="base_width"  value = "0.40"/>
    <property name="base_length" value = "0.60"/>
    <property name="base_height" value = "0.10"/>
    <property name="base_mass"   value = "5"/>

    <link name="base_footprint">
        <inertial>
            <mass value="0.0001" />
            <origin xyz="0 0 0" />
            <inertia
                ixx="0.0000001"
                ixy="0.0"
                ixz="0.0"
                iyy="0.0000001"
                iyz="0.0"
                izz="0.0000001" />
        </inertial>
    </link>

    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child  link="base_link" />
    </joint>

    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value = "${base_mass}" />
            <inertia
            ixx = "${base_mass*(base_width*base_width+base_height*base_height)/12}"
            ixy = "0"
            ixz = "0"
            iyy = "${base_mass*(base_length*base_length+base_height*base_height)/12}"
            iyz = "0"
            izz = "${base_mass*(base_width*base_width+base_length*base_length)/12}"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height} " />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height} " />
            </geometry>
        </collision>
    </link>

    <wheel fb="front" lr="right" parent="base_link" translateX="${(base_length-wheel_radius)/2}"  translateY="${(base_width + wheel_height)/2}"  flipY="1"/>
    <wheel fb="front" lr="left"  parent="base_link" translateX="${(base_length-wheel_radius)/2}"  translateY="-${(base_width + wheel_height)/2}" flipY="1"/>
    <wheel fb="back"  lr="right" parent="base_link" translateX="-${(base_length-wheel_radius)/2}" translateY="${(base_width + wheel_height)/2}"  flipY="1"/>
    <wheel fb="back"  lr="left"  parent="base_link" translateX="-${(base_length-wheel_radius)/2}" translateY="-${(base_width + wheel_height)/2}" flipY="1"/>

    <laser_scanner_link parent="base_link" x="${(base_length-2*laser_scanner_size)/2}" y = "0" z="${(laser_scanner_size+base_height)/2}" r = "0" p ="0" yaw = "0"/>
    <camera_link parent="base_link" x="${(base_length+0.05)/2}" y = "0" z="0" r = "0" p ="0" yaw = "0"/>
    <imu_link parent="base_link" />

    <!--<gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
          <robotNamespace>/fourWD_catbot</robotNamespace>
        </plugin>
    </gazebo> -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_four_wheeled_drive.so">
            <rosDebugLevel> Debug </rosDebugLevel>
            <publishWheelTF>true</publishWheelTF>
            <robotNameSpace>/fourWD_catbot</robotNameSpace>
            <publishTF>1</publishTF>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>50</updateRate>
            <frontLeftJoint>front_left_wheel_joint</frontLeftJoint>
            <frontRightJoint>front_right_wheel_joint</frontRightJoint>
            <backLeftJoint>back_left_wheel_joint</backLeftJoint>
            <backRightJoint>back_right_wheel_joint</backRightJoint>
            <wheelSeparation>0.4</wheelSeparation>
            <wheelDiameter>0.2</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>9.8</wheelAcceleration>
            <commandTopic>catbot/cmd_vel</commandTopic>
            <odometryFrame>catbot/odom</odometryFrame>
            <odometryTopic>catbot/odom</odometryTopic>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <legacyMode>true</legacyMode>
            <odometrySource>encoder</odometrySource>
        </plugin>
    </gazebo>
</robot>
